### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by visjble** [kolyvan/kybook#117]
Looking at the same pdf on kybook2 nightmode works, does not on kybook 3. Paid for it fyi.

**Comment by kolyvan** [comment]
Sorry, but I do not understand your issue.
Could you please provide a bit more details and attach some screenshot?

**Comment by visjble** [comment]
Ok, i am able to change themes on a pdf in kybook2 but not on kybook3 on the SAME pdf. Does it make sense? I would attach screenshots but github does not have an image upload option for this ipad. Suffice to say it’s happening.

**Comment by kolyvan** [comment]
Ok, seems I understand what the problem is.
By default, KyBook 3 does not render PDF or DjVu page in the theme color, since no sense to do that for technical literature. 
But if you wish, you can change that. Just open the book's preferences  and select "Theme book" switch.

![kybook-theme-pdf](https://user-images.githubusercontent.com/791320/51798415-4bc4c380-225d-11e9-9c7b-6f671d5a10f1.png)

P.S. And please, do not raise a trivial question as KyBook issue.
There is the forum for help: http://kybook-reader.com/help

**Comment by visjble** [comment]
That worked, thanks
