### ISSUE TITLE
Unable to open files until processed

### ISSUE THREAD

**Issue by alexmadjar** [kolyvan/kybook#124]
It seems that books undergo some kind of metadata matching when they are added. While helpful, this seems to prevent files from being opened right away when copied into the app. I'd love to be able to open a file as soon as I add it.

**Comment by kolyvan** [comment]
Um, before opening a book it must be processed. There is no way to pass this step.

**Comment by alexmadjar** [comment]
Technically all the data needed to open the file is there in the file itself. I appreciate that perhaps your app is not architected in a way to allow this, however.

**Comment by kolyvan** [comment]
Sorry, but I am unsure what you have knowledge about internal KyBook architecture.
Please, do not make assumption.

**Comment by alexmadjar** [comment]
I am unsure what you think I said but I think we are saying the same thing. No worries @kolyvan

**Comment by kolyvan** [comment]
A bit info about some internal machinery.

KyBook works with books but not with files. 
The book is a database record including an information about files locations, file hashes, metadata and so on.
KyBook can't just open a file (since an user may already has the same file duplicated and have a read position, bookmarks, notes, etc). Before any action KyBook must search in the database about the book record with the same file attributes. 

When KyBook encounter a new file it tries associate this file with some book record. 
In some cases it may require calculating of a file digest (md5 or sha1 hash) to fulfilment a deep search in the database. In some cases KyBook may ask Cloud Storage for such hash sometimes not.

Calculating of a file digest (when Cloud Storage can't provide such hash) may require downloading a file. Downloading and digest calculation requires a some time to completion.

Certainly there are lots of caching and optimization tricks to speed up these steps and the schema above is roughly described. 
But now you know why the file sometimes processed.

**Comment by alexmadjar** [comment]
How does it work in the case of cloud files? Does it have to download the file to the local client first before it can compute the hash?

**Comment by kolyvan** [comment]
> Does it have to download the file to the local client first before it can compute the hash?

First KyBook asks Cloud Storage for a hash. 
Some like Google Drive or OneDrive can provide such hash.
If a hash responsed from Cloud Storage is completely unknown so KyBook must download a file for processing - to obtain the metadata (title, author, cover image), calculating hashes, inserting new book record into the database and so on.

When Cloud Storage can provide a hash and can stream a file (works for PDF and audiobooks),), KyBook can download only a part of file (header).

**Comment by kolyvan** [comment]
And you can pass all KyBook machinery with books loading and processing.
Just go to Advanced UI mode and add "File Browser" widget. 
This tool was developed for working with files (not books) like common file browser.
In FlieBrowser KyBook never automatically downloads or processes any file.
