### ISSUE TITLE
BUG: Crash when opening after copying 12 GB of mixed files in iTunes

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#47]
KyBook 3 v0.5.5 | #95

1. Delete KyBook from iPad and reinstall via TestFlight. 
2. Connect to iTunes and drag and drop 12 GB of mixed files (>500)
3. Open KyBook 3
4. The files get moved into the ‘Book’ folder; KyBook 3 displays books with auto generated covers
5. A second or two later KyBook 3 crashes
6. Reopen KyBook 3 and it displays auto generated covers and crashes
7. Repeat 6. ad infinitum

I shall add the files piecemeal and try to determine which ones cause the crash.

**Comment by kolyvan** [comment]
Most likely OOM issue.
KyBook 3 seems has some troubles with non standard PDFs.

**Comment by karlic** [comment]
That's my gut feeling and some of the PDFs are pretty big. I've got round it by adding books 50 at a time. One batch of 50 did cause a crash, but KyBook 3 was OK after being restarted.

Does KyBook 3 try and process **_all_** the added files at once each on a separate thread? If so, could it process in groups of, say, 20. Or check available memory before taking on more books to process?

**Comment by kolyvan** [comment]
> try and process all the added files at once 

Certainly not. KyBook processed PDF one by one.
But there is a little timeout before resources will be freed after processing done.
And when few huge PDFs processed in a row and the memory are still borrowed (due to the lag), OOM may occurs.

Remarks about PDF support in KyBook.
KyBook 1/2 uses Google PDFium library from Chrome project to render PDF.
KyBook 3 switched to use Apple PDFKit.

Apple PDFKit are much easier to use, no additional IPA size (iOS already include PDFKit), but as drawback PDFKit can't handle some huge, non-standard PDF. It consumes lots of memory and very lazy during freeing a memory.

On the other hand the Google PDFium is fast and memory efficient but very difficult to use. Very difficult to build, integrate and maintain due to great complexity of the library.  And as the result of using PDFium - it takes up a lot of space in IPA file. PDFium will take up to 25MB additionally. For example, now, the size of KyBook3 IPA file is about 40-50MB depends on the target device and 50% size increasing is not good idea.

Later (maybe in winter 2019) I will return to the PDF task and will think again about PDF library. Maybe I will switch back to PDFium depends on user's feedback.
