### ISSUE TITLE
Cosmetic: Excluding all books from a subject deletes the subject

### ISSUE THREAD

**Issue by karlic** [kolyvan/kybook#57]
1. `Cataloguer` -> `Subjects`
2. Long tap a subject 
3. Tap `Exclude`
4. The book(s) and the subject disappear (as expected)
5. Tap a book in the Library view
6. Tap `Edit` on the book card
7. Tap `Add a subject`
8. The subject excluded in step 3. is not available (presumably deleted from the database)

The deletion of the subject is unexpected given the designed behaviour in https://github.com/kolyvan/kybook/issues/40

**Comment by kolyvan** [comment]
It's not the bug.

You can exclude a subject from the database at the Cataloguer/Subjects screen.
And you can exclude a book from the subject at the Catalouger/Subjects/Subject screen.

Excluding a subject from the database in fact deletes a subject.
Excluding a book from subject just deletes a relation between a subject and a book.

Also you can `Delete a subject` additionally to `Exclude` at the Cataloguer/Subjects screen.
Difference between `Delete` and `Exclude` in that `Delete` also deletes all books for this subject.

**Comment by karlic** [comment]
So, `Exclude` or `Delete` in Subjects **_deletes_** empty subjects (https://github.com/kolyvan/kybook/issues/57); `Delete this book` in book card **_leaves_** empty subjects (https://github.com/kolyvan/kybook/issues/40).

**Comment by kolyvan** [comment]
Yes, some inconsistency in terms is exist.

- `Delete empty` action in Cataloguer screen
- `Delete` menu item in Cataloguer screen by tapping on a category 
- `Delete` a category in BookCard during editing
- `Exclude` menu item in Cataloguer screen by tapping on a category 
- Something I forgot

I do not like `Exclude`, it's the compromise because of existing (_or better to say: must have a distinct between_) two different scenarios: delete books with some category and delete only a category itself.
Ideally, `delete` verb must be used only for a destructive action (when books will be deleted).
But in the read-life users do not understand a term `Exclude`
Using `Exclude` (or any other similar term) where it must be used logically will just confuse an ordinal user and we must use `Delete` term despite of illogical.

**Comment by karlic** [comment]
Actually I was NOT referring to the menu items’ names. 

I was referring to the fact that #57 cleans up and #40 does not clean up, which seems inconsistent. 

#57 = empties NOT left behind
#40 = empties ARE left behind
