### ISSUE TITLE
Double page view

### ISSUE THREAD

**Issue by makamoa** [kolyvan/kybook#68]
Could you include double-page regime like it was in KyBook2?

**Comment by karlic** [comment]
@deathproofy Have you turned off the device's rotation lock? And enabled the `Page spread` toggle?
In an EPUB:
1. tap the preferences icon (looks like 3 small sliders)
2. tap the toggle next to `Page spread`
(The device will need to be rotated to landscape to see the two pages.)

If you mean for PDFs, this has been asked before https://github.com/kolyvan/kybook/issues/54. Post up some examples of why you need it and maybe we can convince @kolyvan :-)

If you mean that double-page spread is different from KyBook 2, could you specify what it is that you want? (Your issue is a bit vague.)

**Comment by kolyvan** [comment]
About PDF, how I said before, I plan to think over the PDF implementation in the KyBook at the winter of 2019. Also I will rethink about double-pages. Till winter 2019 I do not plan to do any changes in PDF support.

**Comment by ysn-0711** [comment]
Являюсь пользователем ВСЕХ версий Kybook. Не совсем понимаю, зачем убирать из очередной версии программы фунционал, который был востребован и замечательно работал на предыдущих версиях Kybook. Обычно новая версия должна означать улучшение а не ухудшение! 
Очень нехочется держать две версии читалки ( с библиотеками по 15ГБ каждая) из-за отсутствия разворота в последней версии! Верните, pls.

**Comment by kolyvan** [comment]
Во первых, позвольте Вас поправить. 
Никакая функциональность в KyBook 3 не была убрана (в том числе и разворот страниц). Невозможно убрать то чего никогда не было реализовано. 
KyBook  3 был написан с нуля и никогда не поддерживал разворот страниц для PDF, DjVu.

Причины на то были следующие:
- Нехватка времени и ресурсов
- Мое мнение о том что разворот страниц для PDF/DjVu слабо подходит для текущих экранов мобильных устройств. 

Сколько либо комфортно просмотреть две страницы сразу возможно только на iPad 12.9'', а это редкое ( в случае России, крайне редкое устройство).  Масcовые iPad (9.7'' и 7.9'') не всегда позволяют комфортабельно читать даже одну страницу длокумента PDF не прибегая к постояному зуммированию страницы. iPhone же совсем неподходит для чтения PDF ни в режиме одной страницы ни в режиме разворота.

И как я уже писал выше, зимой 2019 я планирую вернуться к коду PDF/DJVU и возможно код поддержки PDF будет радикально изменен если я найду это необходимым. Поэтому до зимы я не буду делать каких-либо изменений в коде модулей PDF/DJVU.

-- English translation --

First, let me correct you.
No functionality in KyBook 3 has been removed (including page spreads).
Because it is impossible to remove something that has never been implemented.
KyBook 3 was development from scratch and never has a page spread feature for PDF, DjVu.

The reasons:
- Lack of time and resources
- My opinion is that PDF double-pages is poorly fitted into current screens of mobile devices.

Only iPad 12'' is suitable device for comfortable viewing of PDF page-spread. But iPad 12.9'' is not very common device. Ordinary iPads (7.9'' and 9.7'') do not always allow user to comfortably read even one page of a PDF document without constant page zooming. iPhone is completely not suitable for reading PDF in either single-page or double-page mode.

And as I wrote above, I plan to return to the PDF / DJVU code in winter 2019. And maybe PDF code will be radically rewritten if I deem it necessary. Therefore, until winter, I will not make any changes in the PDF / DJVU modules.

**Comment by ysn-0711** [comment]
Спасибо за развернутый ответ. Очень хотелось бы видеть зимой эту возможность. Как мы с Вами уже обсуждали при разработке Вами 1 и 2 версий, в медицине очень много учебников и атласов где диаграммы и схемы печатаются на двух страницах, и очень неудобно туда сюда листать и сопоставлять одну страницу с другой. Это не просто хотелки, а очень нужная и полезная функция. Спасибо.

**Comment by karlic** [comment]
@ysn-0711 I have raised this issue before (https://github.com/kolyvan/kybook/issues/54) as I find the iPad **_Mini_** perfectly big enough, even with old-man's eyesight. I have recently been on holiday and was unable to use most of my 350+ PDFs (travel guides with maps, flora & fauna reference books, etc.). **_I came to the conclusion that KyBook 3 is not yet suitable for PDF reading_** (even single page reading is unbearable as there is no rotation lock on iPad) and a year is too long to wait. I used KyBook 2 whilst away and have decided to move all my books back to KyBook 2. I'm currently writing a Python script to sync books from Calibre to KyBook 2 (based on https://github.com/kovidgoyal/calibre/blob/master/src/calibre/devices/smart_device_app/driver.py) and will post it on Github when complete, if you want to do the same. I hope that helps. 

----- Google translate -----
@ ysn-0711 Я поднял эту проблему раньше (# 54), поскольку я нахожу iPad Mini совершенно достаточно большим, даже со зрением старика. Я недавно был в отпуске и не смог использовать большинство моих 350+ PDF-файлов (путеводители с картами, справочники по флоре и фауне и т. Д.). Я пришел к выводу, что KyBook 3 еще не подходит для чтения PDF (даже одностраничное чтение невыносимо, поскольку на iPad нет блокировки вращения), а год слишком долго ждать. Я использовал KyBook 2 в то время как прочь и решил переместить все мои книги обратно в KyBook 2. В настоящее время я пишу скрипт Python для синхронизации книг от Caliber до KyBook 2 и опубликую его на Github, когда закончите, если вы хотите сделать так же. Надеюсь, это поможет.

**Comment by ysn-0711** [comment]
Thank you! While we are waiting for improved Kybook 3, we'll use the 2nd version of this book reader.

**Comment by karlic** [comment]
If/when double-page spread is added, please could you allow for "offsetting" by one page, to account for the first page being a cover as Goodreader does?

**Comment by kolyvan** [comment]
Done in v0.6.5

**Comment by ysn-0711** [comment]
Спасибо огромное!

С наилучшими пожеланиями,

Сергей Н.Юхимец
8 дек. 2018 г., 5:49 +0300, Konstantin Boukreev <notifications@github.com>, писал:
