### ISSUE TITLE
Advanced interface tab

### ISSUE THREAD

**Issue by tsroman** [kolyvan/kybook#94]
When using advanced interface + Hide header bar.
My book always redraws because of changed layout when I open a menu in order to pick other tab or settings.
Can you please fix that?
The best solution for me just draws tabs menu on text (do not change a layout of the entire book) when "Hide header bar" is active, or make another checkbox to enable this.

**Comment by kolyvan** [comment]
Sorry, but what you asking is not possible to implement.

When you toggling the fullscreen in the advanced interface the reader size is changed (reduced due to top bars) so the content must be re-layouted to fit changed size.

You can switch to the default interface mode or use scrolling instead of pagination.

**Comment by tsroman** [comment]
I do not like scrolling... What a reason to change reader size when people with enabled "Hide header bar" option read a book on full-screen anyway.
Do I need to open the menu to switch tab, to translate, check bookmarks why should I wait extra time to redraw for such a simple reason? Do you understand that this is completely annoying?
What if you just move reader down like how it works in kybook2 and in extra make current page scrollable? (for people with "Hide header bar" enabled)
