### ISSUE TITLE
upgrade to kybook 3 pro not taken into account

### ISSUE THREAD

**Issue by ambh94** [kolyvan/kybook#95]
I paid un upgrade to kybook pro 3 from kybook 2 the 28th of september 2018. It worked fine, but I got a new Ipad, and not using anymore the old one,  and reinstalled my kybook pro 3 which ask me now to pay for a new upgrade to kybook pro 3. I have already paid for this updrade. My email with Itunes is ambh@free.fr. Please answer me quickly, otherwise, i will contact apple for this incident.

**Comment by karlic** [comment]
Have you tried the `Restore purchases` button?
1. Tap `Control` (looks like a gear wheel)
2. Tap `In-App Purchases`
You should see it in red at the top of the page. 

Otherwise, post details of what versions of iOS and KyBook 3 you have and what you have tried so far.  I suspect if `Restore purchases` doesn’t work, you’ll need to contact Apple anyway.

**Comment by ambh94** [comment]
Thanks a lot, it was the right answer..

I appréciante very much your ebook reader.

Good luck

**Comment by karlic** [comment]
I’m glad it’s sorted. 

> I appréciante very much your ebook relder

:-) I wish, but I’m sure @kolyvan will be pleased to read that.

**Comment by kolyvan** [comment]
Thank you @karlic for your response and help.
